name: MarvelCharacters
options:
  bundleIdPrefix: com.Globant.MarvelCharacters.MarvelCharacters
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 14.0
targets:
  MarvelCharacters:
    type: application
    platform: iOS
    sources:
      - path: MarvelCharacters
    dependencies:
      - package: Kingfisher
      - package: Moya
    scheme:
      testTargets:
      - MarvelCharactersTests
  MarvelCharactersTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MarvelCharactersTests
    dependencies:
      - target: MarvelCharacters
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    majorVersion: 7.0.0
  Moya:
    url: https://github.com/Moya/Moya.git
    majorVersion: 15.0.0

